Travel_Agency/Travel_Agency/Models/Leg.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Travel_Agency.Models
{
    public class Leg
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "Start Location Is Required")]
        public String StartLocation { get; set; }

        [Required(ErrorMessage = "Finish Location Is Required")]
        public String FinishLocation { get; set; }

        [Required(ErrorMessage = "Start Date Required")]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        [DataType(DataType.Date)]
        public DateTime StartDate { get; set; }

        [Required(ErrorMessage = "Finish Date Required")]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        [DataType(DataType.Date)]
        public DateTime FinishDate { get; set; }

        public int TripID { get; set; }

        public virtual ICollection<Guest> Guests { get; set; }
        public virtual Trip Trip { get; set; }
    }
}

Travel_Agency/Travel_Agency/Controllers/GuestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Travel_Agency.DAL;
using Travel_Agency.Models;

namespace Travel_Agency.Controllers
{
    public class GuestController : Controller
    {
        private ITravelRepository _repo;

        public GuestController(ITravelRepository repo)
        {
            _repo = repo;
        }        

        public ActionResult AddGuest(int id)
        {
            var q = _repo.GetLegById(id);
            ViewBag.Guests = _repo.GetAllGuestNames();
            return PartialView("_AddGuest", q);
        }
        
    }
}

Travel_Agency/Travel_Agency/Controllers/LegsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using Travel_Agency.DAL;
using Travel_Agency.Models;
using HtmlAgilityPack;

namespace Travel_Agency.Controllers
{
    public class LegsController : Controller
    {
        private ITravelRepository _repo;

        public LegsController(ITravelRepository repo)
        {
            _repo = repo;
        }

        // GET api/legs/5
        public ActionResult GetLegs(int id)
        {
            var q = _repo.GetLegsForTrip(id).FirstOrDefault();
            if (q != null)
            {
                ViewBag.Viable = q.Trip.Viable;
            }
            
            
            ViewBag.tripname = _repo.GetTripName(id);
            ViewBag.tripId = id;            
            return PartialView("_TripLeg", _repo.GetLegsForTrip(id));
        }        

        public ActionResult GetDetails(int legid)
        {
            List<String> names = new List<String>();
            var q = _repo.GetLegById(legid);
            //get start location image url
            ViewBag.StartLocation = GetLocationURL(q.StartLocation);
            ViewBag.EndLocation = GetLocationURL(q.FinishLocation);
            foreach (Guest g in q.Guests)
            {
                names.Add(g.FirstName);
            }
            ViewBag.Guests = names;

            return PartialView("_LegDetails", q);
        }
                
        private string GetLocationURL(string p)
        {
            List<String> sources = new List<String>();
            HtmlWeb web = new HtmlWeb();
            HtmlDocument doc = web.Load("http://en.wikipedia.org/wiki/" + p);
            var nodes = doc.DocumentNode.SelectNodes("//img[@src]");
            sources = nodes == null ? new List<string>() : nodes.ToList().ConvertAll(r => r.Attributes.ToList().ConvertAll(i => i.Value)).SelectMany(j => j).ToList();
            string lower = "";
            foreach (string s in sources)
            {
                lower = s.ToLower();
                if (lower.Contains("commons") && lower.Contains("collage") || lower.Contains("commons") && lower.Contains("montage") || (((lower.Contains("montage") && lower.Contains("commons")) && (lower.Contains("jpg") || lower.Contains("png")))))
                {
                    return s;
                }
            }
            return "";
        }

        [HttpGet]
        public ActionResult Create(int id)
        {
            //HtmlHelper.UnobtrusiveJavaScriptEnabled = true;
            ViewBag.TripID = id; 
            return PartialView("_CreateLeg");
        }

    }
}

Travel_Agency/Travel_Agency/Views/Legs/_CreateLeg.cshtml
@model Travel_Agency.Models.Leg

@{
    int tripId = ViewBag.TripID;
}
<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css">

<div class="modal fade" id="legModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Add New Leg</h4>
            </div>
            <div class="modal-body">
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)
                <div class="form-group">
                    @Html.LabelFor(model => model.StartLocation)
                    @Html.TextBoxFor(model => model.StartLocation, new { @class = "form-control", placeholder = "Start Location" })
                    @Html.ValidationMessageFor(model => model.StartLocation)
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.FinishLocation)
                    @Html.TextBoxFor(model => model.FinishLocation, new { @class = "form-control ", placeholder = "Finish Location"})
                    @Html.ValidationMessageFor(model => model.FinishLocation, null, new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.StartDate)
                    @Html.TextBoxFor(model => model.StartDate, new { @class = "form-control ", placeholder = "mm/dd/yyyy" })
                    @Html.ValidationMessageFor(model => model.StartDate, null, new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.FinishDate)
                    @Html.TextBoxFor(model => model.FinishDate, new { @class = "form-control ", placeholder = "mm/dd/yyyy" })
                    @Html.ValidationMessageFor(model => model.FinishDate, null, new { @class = "text-danger" })
                </div>
            </div>
            <div id="error" style="visibility:hidden; color:red;">
                <h4>Error Creating New Leg</h4>
            </div>
            <div class="modal-footer">
                <form class="form-inline" role="form">
                    <div class="form-group">
                        <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
                    </div>
                    <div class="form-group">
                        <button id="submit" class="btn btn-primary ">
                            <i class="glyphicon glyphicon-plus-sign"></i> Create
                        </button>
                    </div>
                </form>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->


<script>
    $(function () {

        $('#StartDate').datepicker({ dateFormat: 'mm/dd/yy' });
        $('#FinishDate').datepicker({ dateFormat: 'mm/dd/yy' });

        $("#submit").click(function (e) {
            e.preventDefault();
            var newLeg = {
                StartLocation: $("#StartLocation").val(),
                FinishLocation: $("#FinishLocation").val(),
                StartDate: $("#StartDate").val(),
                FinishDate: $("#FinishDate").val(),
                TripId: '@ViewBag.TripID'
            }
            sendLeg(newLeg);
        });


        function sendLeg(leg) {
            //alert("got in")
            $.ajax({
                url: "http://localhost:49775/api/LegApi/Post",
                data: JSON.stringify(leg),
                type: "POST",
                contentType: "application/json;charset=utf-8",
                success: function (data) {
                    //alert(data)
                    toastr.success('Leg Created!!');
                    setTimeout(function () {
                        window.location.href = ("/Home/Index");
                    }, 1000);
                    
                },
                error: function (error) {
                    //alert(JSON.stringify(error));
                    $("#error").css('visibility', 'visible');
                }
            });
        }
    });

</script>

Travel_Agency/Travel_Agency/Views/Legs/_EmptyLeg.cshtml
<tr>
    <td><button class="btn btn-xs btn-primary" onclick="AddLeg(@ViewBag.tripId)">Add Leg</button></td>
</tr>

Travel_Agency/Travel_Agency/Views/Legs/_LegDetails.cshtml
@model Travel_Agency.Models.Leg

<div class="modal fade" id="detailModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Details Of Leg</h4>
            </div>
            <div class="modal-body">
                @{Html.RenderPartial("_LegInfo");}
            </div>
            <div class="modal-footer">
                <form class="form-inline" role="form">
                    <div class="form-group">
                        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                    </div>
                </form>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

Travel_Agency/Travel_Agency/Views/Legs/_LegInfo.cshtml
@model Travel_Agency.Models.Leg

<div class="row">
    <div class="col-md-4">
        <img height="200" width="150" src="@ViewBag.StartLocation" />
    </div>
    <div class="col-md-8">
        <h3>Starting in @Model.StartLocation</h3>
        <p>Date : @Model.StartDate.ToShortDateString()</p>
    </div>
</div>
<br />
<div class="row">
    <div class="col-md-4">
        <img height="200" width="150" src="@ViewBag.EndLocation">
    </div>
    <div class="col-md-8">
        <h3>Finishing in @Model.FinishLocation</h3>
        <p>Date : @Model.FinishDate.ToShortDateString()</p>
    </div>
</div>
<div class="row">
    <div class="col-md-4">
        <p></p>
    </div>
    <div class="col-md-8">
        <h4>Guests Travelling:</h4>
        <h5 id="gp"></h5>
    </div>
</div>

<script>
    $( document ).ready(function() {

        var array = @Html.Raw(Json.Encode(ViewBag.Guests));
        for(var i = 0; i < array.length; i++) {
            document.getElementById('gp').innerHTML += (array[i] + "; ");            
        }

    });

</script>

Travel_Agency/Travel_Agency/Views/Legs/_LegOk.cshtml
@model Travel_Agency.Models.Leg

<tr id="@Model.ID">
    <td>
        @Html.DisplayFor(modelItem => Model.StartLocation)
    </td>
    <td>
        @Html.DisplayFor(modelItem => Model.FinishLocation)
    </td>
    <td>
        @Html.DisplayFor(modelItem => Model.StartDate, "ShortDateTime")
    </td>
    <td>
        @Html.DisplayFor(modelItem => Model.FinishDate, "ShortDateTime")
    </td>
    <td>
        @Html.DisplayFor(modelItem => Model.Guests.Count)
    </td>
    <td>
        <button class="btn btn-success btn-xs" onclick="AddGuests(@Model.ID)">Add Guests</button> 
        <br /> 
        <button class="btn btn-info btn-xs" onclick="GetLegDetails(@Model.ID)">View Details</button>        
    </td>
</tr>


<script>

    function GetLegDetails(id){
        $("#loader1").css('display', 'block');
        $.ajax({
            url: '@Url.Action("GetDetails", "Legs")',
            data: { legid: id },
            success: function (data) {
                $("#legDetail").html(data);
                $("#detailModal").modal('show');
                $("#loader1").css('display', 'none');
            }
        });
    }

    function AddGuests(id) {
        $("#loader1").css('display', 'block');
        $.ajax({
            url: '@Url.Action("AddGuest", "Guest")',
            data: { id: id },
            success: function (data) {
                $("#loader1").css('display', 'none');
                $("#guestModal").html(data);
                $('#gModal').modal('show');
            }
        });

    }
    
        
</script>
   

Travel_Agency/Travel_Agency/Views/Legs/_TripLeg.cshtml
@model IEnumerable<Travel_Agency.Models.Leg>
@{
    Nullable<DateTime> endOfLastLeg = null;
    bool ok = true;
    int legCount = 0;
    bool gaps = true;    
}

@if (Model.Any())
{
    
    <table class="table table-bordered table-condensed">
        <tr>
            <th>
                Start Location
            </th>
            <th>
                Finish Location
            </th>
            <th>
                Start Date
            </th>
            <th>
                Finish Date
            </th>
            <th>
                Guests
            </th>            
            <th></th>
        </tr>
        @foreach (var item in Model)
        {            
            legCount ++;
            if (endOfLastLeg == null)
            {
                endOfLastLeg = item.Trip.StartDate.Date;
            }//end if

            if (!ok)
            {
                endOfLastLeg = item.StartDate.Date;
            }

            if (item.StartDate.Date != endOfLastLeg && item.FinishDate.Date < item.Trip.FinishDate.Date && item.Trip.Legs.Count == 1)
            {
                Html.RenderPartial("_EmptyLeg");
                Html.RenderPartial("_LegOk", item);
                gaps = false;
            }

            else if (item.StartDate.Date != endOfLastLeg && item.FinishDate.Date < item.Trip.FinishDate.Date && item.Trip.Legs.Count == legCount && item.Trip.Legs.Count != 1)
            {
                Html.RenderPartial("_EmptyLeg");
                ok = false; 
            }//end if
                
            else if (legCount == Model.Count() && item.FinishDate.Date == item.Trip.FinishDate.Date && item.StartDate.Date != endOfLastLeg.Value.Date)
            {
                Html.RenderPartial("_EmptyLeg");
                Html.RenderPartial("_LegOk", item);
                gaps = false;	        
	        }
                
            else if (item.StartDate.Date != endOfLastLeg && item.FinishDate.Date < item.Trip.FinishDate.Date && legCount < item.Trip.Legs.Count)
            {
                Html.RenderPartial("_EmptyLeg");
                Html.RenderPartial("_LegOk", item);
                gaps = false;            
	        }
                                                
            else 
            {
                Html.RenderPartial("_LegOk", item); 
            }//end else

            if (legCount == Model.Count() && item.FinishDate.Date != item.Trip.FinishDate.Date)
            {
                Html.RenderPartial("_EmptyLeg");
                ok = false;
                gaps = false; 
            }
            
            if (ok)
            {
                endOfLastLeg = item.FinishDate.AddDays(1).Date;
            }
            

        }@*end foreach*@
    </table>
}
else //if the trip has no legs
{
    <table class="table table-bordered table-condensed">
        <tr>
            <th>
                Start Location
            </th>
            <th>
                Finish Location
            </th>
            <th>
                Guests
            </th>            
            <th></th>
        </tr>
        <tr>
            @{Html.RenderPartial("_EmptyLeg");}
        </tr>
        </table>
}
<div id="legCreate"></div>
<div id="guestModal"></div>



    <script>

        $(document).ready(function () {
            if ('@Model.Any()' == 'False') {
                toastr.error('This Trip Has No Legs');
            }
            else if ('@gaps' == 'False') {
                toastr.warning("This Trip Has Gaps");
            }
            else {
                toastr.success('All ' + @legCount + ' Legs Retrieved');
            }

            if ('@ViewBag.Viable' == 'False') {
                toastr.warning("This Trip Is Not Viable");
            }
            
        });


        $("#legName").text("Legs For: " + '@ViewBag.tripname');
        
        function AddLeg(id) {
            $("#loader1").css('display', 'block');
            $.ajax({
                url: '@Url.Action("Create", "Legs")',
                data: { id: id },
                success: function (data) {
                    $("#loader1").css('display', 'none');
                    $("#legCreate").html(data);
                    $("#legModal").modal('show');                    
                }
            })
        }
                
        
    </script>