Travel_Agency/Travel_Agency/Models/Trip.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Travel_Agency.Models
{
    public class Trip
    {
        public int ID { get; set; }

        [Display(Name = "Trip Name")]
        [Required(ErrorMessage = "Name Is Required")]
        public String Name { get; set; }


        [Required(ErrorMessage = "Start Date Required")]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        [DataType(DataType.Date)]
        public DateTime StartDate { get; set; }


        [Required(ErrorMessage = "Finish Date Required")]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        [DataType(DataType.Date)]
        public DateTime FinishDate { get; set; }

        //[Required(ErrorMessage = "Min Guests Is Required")]
        [Range(3, 10, ErrorMessage = "{0} has to be a number between {1} and {2}")]
        [Display(Name = "Min Guests")]
        public int MinGuests { get; set; }

        public bool Viable { get; set; }
        public bool Complete { get; set; }

        public virtual ICollection<Leg> Legs { get; set; }
    }
}

Travel_Agency/Travel_Agency/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using Travel_Agency.DAL;

namespace Travel_Agency.Controllers
{
    public class HomeController : Controller
    {
        private ITravelRepository _repo;

        public HomeController(ITravelRepository repo)
        {
            _repo = repo;
        }
        public ActionResult Index()
        {
            return View(_repo.GetAllTrips());
        }

        public ActionResult Create()
        {
            return PartialView("_AddTrip");
        }
        
        protected override void Dispose(bool disposing)
        {
            _repo.Dispose();
            base.Dispose(disposing);
        }
    }
}

Travel_Agency/Travel_Agency/Controllers/LegsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using Travel_Agency.DAL;
using Travel_Agency.Models;
using HtmlAgilityPack;

namespace Travel_Agency.Controllers
{
    public class LegsController : Controller
    {
        private ITravelRepository _repo;

        public LegsController(ITravelRepository repo)
        {
            _repo = repo;
        }

        // GET api/legs/5
        public ActionResult GetLegs(int id)
        {
            var q = _repo.GetLegsForTrip(id).FirstOrDefault();
            if (q != null)
            {
                ViewBag.Viable = q.Trip.Viable;
            }
            
            
            ViewBag.tripname = _repo.GetTripName(id);
            ViewBag.tripId = id;            
            return PartialView("_TripLeg", _repo.GetLegsForTrip(id));
        }        

        public ActionResult GetDetails(int legid)
        {
            List<String> names = new List<String>();
            var q = _repo.GetLegById(legid);
            //get start location image url
            ViewBag.StartLocation = GetLocationURL(q.StartLocation);
            ViewBag.EndLocation = GetLocationURL(q.FinishLocation);
            foreach (Guest g in q.Guests)
            {
                names.Add(g.FirstName);
            }
            ViewBag.Guests = names;

            return PartialView("_LegDetails", q);
        }
                
        private string GetLocationURL(string p)
        {
            List<String> sources = new List<String>();
            HtmlWeb web = new HtmlWeb();
            HtmlDocument doc = web.Load("http://en.wikipedia.org/wiki/" + p);
            var nodes = doc.DocumentNode.SelectNodes("//img[@src]");
            sources = nodes == null ? new List<string>() : nodes.ToList().ConvertAll(r => r.Attributes.ToList().ConvertAll(i => i.Value)).SelectMany(j => j).ToList();
            string lower = "";
            foreach (string s in sources)
            {
                lower = s.ToLower();
                if (lower.Contains("commons") && lower.Contains("collage") || lower.Contains("commons") && lower.Contains("montage") || (((lower.Contains("montage") && lower.Contains("commons")) && (lower.Contains("jpg") || lower.Contains("png")))))
                {
                    return s;
                }
            }
            return "";
        }

        [HttpGet]
        public ActionResult Create(int id)
        {
            //HtmlHelper.UnobtrusiveJavaScriptEnabled = true;
            ViewBag.TripID = id; 
            return PartialView("_CreateLeg");
        }

    }
}

Travel_Agency/Travel_Agency/Controllers/TripsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Mvc;
using Travel_Agency.DAL;
using Travel_Agency.Models;

namespace Travel_Agency.Controllers
{
    public class TripsController : Controller
    {
        private ITravelRepository _repo;

        public TripsController(ITravelRepository repo)
        {
            _repo = repo;
        }

        [HttpGet]
        public ActionResult Create()
        {
            return PartialView("_CreateTrip");
        }
        
    }
}

Travel_Agency/Travel_Agency/Views/Home/Index.cshtml
@model IEnumerable<Travel_Agency.Models.Trip>

@{
    ViewBag.Title = " Available Trips";
}

@section scripts
{
    <script>

        $(document).ready(function () {
            toastr.success('All ' + @Model.Count() + ' Trips Retrieved');
        });

        function GetLegs(TripId) {
            $("#loader1").css('display', 'block');
            //alert(TripId);
            $.ajax({
                url: '@Url.Action("GetLegs", "Legs")',
                data: { id: TripId },
                success: function (data) {
                    $("#tblTripLegs").html(data);
                    $("#loader1").css('display', 'none');
                }
            })
        }

    $("#createT").click(function () {
                
        var newTrip = {
            Name: $("#Name").val(),
            StartDate: $("#StartDate").val(),
            FinishDate: $("#FinishDate").val(),
            MinGuests: $("#MinGuests").val()
        };
        sendTrip(newTrip);
    });            

    function sendTrip(t) {
                
        $.ajax({
            url: "api/TripApi/Post",
            data: JSON.stringify(t),
            type: "POST",
            contentType: "application/json;charset=utf-8",
            success: function (data) {
                window.location.href = ("/Home/Index");
            },
            error: function (error) {
            }
        });

    }
    
    </script>
}


<div class="page-header">
    <h1>A Wing And A Prayer Travel</h1>
</div>
<div class="row">
    <div class="col-md-6">
        <div class="panel panel-info">
            <div class="panel-heading"><strong>Available Trips</strong></div>
            <div class="panel-body" id="tblTrips">
                @{Html.RenderPartial("_Trips", Model);}
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="panel panel-info">
            <div class="panel-heading"><strong id="legName">Legs For ....</strong></div>
            <div class="panel-body" id="tblTripLegs">                
            </div>
        </div>
    </div>    
</div>
<div id="guestModal"></div>
<div id="legDetail"></div>
<div id="loader1" class="text-center" style="display: none;">
    <img src="~/Images/loader.gif" height="80" width="80" />
    <br />
    <h4>Loading ...</h4>    
</div>

Travel_Agency/Travel_Agency/Views/Home/_TripRows.cshtml
@model Travel_Agency.Models.Trip

<td>
    @Html.DisplayFor(modelItem => Model.Name)
</td>
<td>
    @Html.DisplayFor(modelItem => Model.StartDate, "ShortDateTime")
</td>
<td>
    @Html.DisplayFor(modelItem => Model.FinishDate, "ShortDateTime")
</td>
<td>
    @Html.DisplayFor(modelItem => Model.MinGuests)
</td>
<td>
    <button onclick="GetLegs(@Model.ID)" class="btn btn-xs btn-info">View Legs</button>
</td>   

Travel_Agency/Travel_Agency/Views/Home/_Trips 1.cshtml
@model IEnumerable<Travel_Agency.Models.Trip>

<table class="table table-condensed table-bordered">
    <tr>
        <th>
            Name
        </th>
        <th>
            Start Date
        </th>
        <th>
            Finish Date
        </th>
        <th>
            Min Guests
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {

        if (item.Viable && item.Complete)
        {            
            <tr class="success" onclick="getLegs(@item.ID)">
                @{Html.RenderPartial("_TripRows", item);}                
            </tr>
        }
        else if (!item.Viable && !item.Complete)
        {
            <tr class="danger" onclick="getLegs(@item.ID)">
                @{Html.RenderPartial("_TripRows", item);}                
            </tr>
        }
        else
        {
            <tr class="warning" onclick="getLegs(@item.ID)">
                @{Html.RenderPartial("_TripRows", item);}                
            </tr>
        }

    }
</table>

<button onclick="AddTrip()" class="btn btn-primary" >Add Trip</button>


    <script>
        function AddTrip() {
            $.ajax({
                url: '@Url.Action("Create", "Trips")',
                success: function (data) {
                    $("#tripCreate").html(data);
                    $("#tripModal").modal('show');
                }
            })
        }
    </script>

Travel_Agency/Travel_Agency/Views/Home/_Trips.cshtml
@model IEnumerable<Travel_Agency.Models.Trip>

<table class="table table-condensed table-bordered">
    <tr>
        <th>
            Name
        </th>
        <th>
            Start Date
        </th>
        <th>
            Finish Date
        </th>
        <th>
            Min Guests
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {

        if (item.Viable && item.Complete)
        {            
            <tr class="success">
                @{Html.RenderPartial("_TripRows", item);}                
            </tr>
        }
        else if (!item.Viable && !item.Complete)
        {
            <tr class="danger">
                @{Html.RenderPartial("_TripRows", item);}                
            </tr>
        }
        else
        {
            <tr class="warning">
                @{Html.RenderPartial("_TripRows", item);}                
            </tr>
        }

    }
</table>
<div class="row">
    <button onclick="AddTrip()" class="btn btn-primary btn-sm col-sm-2">Add Trip</button>
    </div>
<div class="row">
    <h6 class="col-sm-4">Trip Viable And Complete<span class="label label-success ">     </span></h6>
    <h6 class="col-sm-4">Trip Not Viable <strong>Or</strong> Not Complete<span class="label label-warning ">     </span></h6>
    <h6 class="col-sm-4">Trip Not Viable <strong>And</strong> Not Complete<span class="label label-danger">     </span></h6>
</div>
<div id="tripCreate"></div>

<script>
    function AddTrip() {
        $("#loader1").css('display', 'block');
        $.ajax({
            url: '@Url.Action("Create", "Trips")',
            success: function (data) {
                $("#tripCreate").html(data);
                $("#tripModal").modal('show');
                $("#loader1").css('display', 'none');
            }
        })
    }
</script>